// GENERATED-STYLE FILE — machine-draft literary translations.
// Keyed as: DRAFT_DATA[moduleId][sceneId][field][langCode] = "translated text".
// These are UNREVIEWED machine translations (drafted in-session by Claude, the same capability the
// `gen:claude-drafts` script invokes via API) and are labelled "machine translation, unreviewed" in the
// Reader (integrity rule — no fabricated authority). EN + Setswana (tn) live in the content modules as
// human-reviewed copy and are NOT duplicated here. Proper nouns and culturally-specific terms
// (inkundla, ubulungisa, umthetho, izimbongi, sanusi, Ninavanhu-Ma, Re-Nosi, Mfecane, …) are kept in
// their original form, with a short gloss only where the English already glosses them.
//
// Languages: af (Afrikaans), zu (isiZulu), xh (isiXhosa), nso (Sepedi), st (Sesotho), ss (siSwati),
// ts (Xitsonga), nr (isiNdebele), ve (Tshivenḓa). Needs a native-speaker review before it counts.
export const DRAFT_DATA: Record<
  string,
  Record<string, Record<string, Record<string, string>>>
> = {
  mhudi: {
    "forest-home": {
      title: {
        af: "Die Woudtuiste",
        zu: "Ikhaya Lasehlathini",
        xh: "Ikhaya Lasehlathini",
        nso: "Legae la Sethokgweng",
        st: "Lehae la Morung",
        ss: "Likhaya Lasehlatsini",
        ts: "Kaya ra Nhoveni",
        nr: "Ikhaya Lehlathini",
        ve: "Hayani ha Ḓakani",
      },
      text: {
        af: "Nadat die Matabele-aanval die Barolong verstrooi en die stad Kunana verwoes het, het Mhudi en Ra-Thaga mekaar as oorlewendes in die wildernis ontmoet. Ver van die oudstes en die verpligtinge van die dorp het hulle 'n eie tuiste gebou en dit Re-Nosi genoem — 'Ons-is-alleen.' Hul verbintenis is nie deur gebruik gereël nie, maar in oorlewing gesmee, gegrond op wedersydse respek.",
        zu: "Ngemva kokuba ukuhlasela kwamaNdebele kuhlakaze abakwaBarolong futhi kwabhubhisa idolobha laseKunana, uMhudi noRa-Thaga bahlangana bengabasindile ehlane. Kude nabadala nezibopho zomuzi, bakha ikhaya labo balibiza ngokuthi Re-Nosi — 'Sisodwa.' Ukuhlangana kwabo akuzange kuhlelwe ngesiko, kepha kwakhandwa ekusindeni, kusekelwe enhloniphweni yomunye nomunye.",
        xh: "Emva kokuba uhlaselo lwamaNdebele luchithachithe amaBarolong laza latshabalalisa idolophu yaseKunana, uMhudi noRa-Thaga badibana bengabasindileyo entlango. Kude kubadala nakwiimbopheleleko zelali, bakha ikhaya labo baza balibiza ngokuba yiRe-Nosi — 'Sisodwa.' Umanyano lwabo aluzange lulungiselelwe sisiko, koko lwakhandwa ekusindeni, lusekelwe kwintlonelo yomnye nomnye.",
        nso: "Ka morago ga ge tlhaselo ya Matebele e phatlaladitše Barolong gomme ya senya motse wa Kunana, Mhudi le Ra-Thaga ba kopana e le baphologi lešokeng. Kgole le bagolo le maikarabelo a motse, ba aga legae la bona gomme ba le bitša Re-Nosi — 'Re nnoši.' Lenyalo la bona ga se la ka la beakanywa ke setšo, la bopša tabološong ya go phologa, le theilwe godimo ga tlhompho ya go fapana.",
        st: "Ka mora ha tlhaselo ya Matebele e qhalakantse Barolong mme ya senya motse wa Kunana, Mhudi le Ra-Thaga ba kopana e le baphonyohi lehwatateng. Hole le baholo le boikarabelo ba motse, ba aha lehae la bona mme ba le bitsa Re-Nosi — 'Re le rong.' Lenyalo la bona ha le a ka la hlophisoa ke moetlo, le entsoe pholohong, le thehiloe holim'a tlhompho ya ho fapana.",
        ss: "Ngemva kwekutsi kuhlasela kwemaNdebele kuhlakate emaBarolong futsi kwabhubhisa lidolobha laseKunana, Mhudi naRa-Thaga bahlangana babasindzile ehlane. Kude nalabadzala netibopho temuti, bakha likhaya labo balibita ngekutsi yiRe-Nosi — 'Sisodvwa.' Kuhlangana kwabo akuzange kuhlelwe ngelisiko, kodvwa kwakhandvwa ekusindzeni, kusekelwe enhlonipheni yalomunye nalomunye.",
        ts: "Endzhaku ka loko nhlaselo wa Matebele wu hangalase Barolong kutani wu onha muti wa Kunana, Mhudi na Ra-Thaga va hlangana va ri lava poneke enhoveni. Ekule ni vakulukumba ni vutihlamuleri bya muti, va aka kaya ra vona kutani va ri thya Re-Nosi — 'Hi hi vote.' Vukati bya vona a byi lulamisiwanga hi ndhavuko, kambe byi vumbiwile eku poneni, byi simekiwe ehenhla ka xichavo xa un'wana na un'wana.",
        nr: "Ngemva kobana ukuhlasela kwamaNdebele kuhlakaze amaBarolong begodu kwatjhabalalisa idorobho leKunana, uMhudi noRa-Thaga bahlangana babasindileko ehlathini. Kude nabadala neembopho zomuzi, bakha ikhaya labo balibiza ngokuthi yiRe-Nosi — 'Sisodwa.' Ukuhlangana kwabo akhange kuhlelwe ngesiko, kodwana kwakhiwa ekusindeni, kusekelwe ehloniphweni yomunye nomunye.",
        ve: "Nga murahu ha musi nyanḓadzo ya Matebele yo phaḓaladza Vharolong nahone ya tshinyadza muḓi wa Kunana, Mhudi na Ra-Thaga vha ṱangana vhe vhaponyoki sogani. Kule na vhahulwane na mishumo ya muḓi, vha fhaṱa hayani ḽavho nahone vha ḽi vhidza Re-Nosi — 'Ri roṱhe.' Mbingano yavho a yo ngo dzudzanywa nga sialala, yo vhumbwa kha u ponyoka, yo thewa kha ṱhonifho ya muṅwe na muṅwe.",
      },
      childText: {
        af: "Lank gelede het 'n groot aanval Mhudi se mense verstrooi en haar dorp verwoes. Alleen in die wildernis het Mhudi vir Ra-Thaga ontmoet, nog 'n oorlewende. Saam het hulle 'n klein tuiste gebou en dit Re-Nosi genoem, wat 'Ons is alleen' beteken. Hulle het vir mekaar omgegee en mekaar gerespekteer.",
        zu: "Endulo, ukuhlasela okukhulu kwahlakaza abantu bakaMhudi kwabhubhisa nedolobha lakhe. Eyedwa ehlane, uMhudi wahlangana noRa-Thaga, omunye owasinda. Ndawonye bakha ikhaya elincane balibiza ngoRe-Nosi, okusho ukuthi 'Sisodwa.' Babenakekelana futhi behloniphana.",
        xh: "Kudala, uhlaselo olukhulu lwabachithachitha abantu bakaMhudi lwatshabalalisa nedolophu yakhe. Eyedwa entlango, uMhudi wadibana noRa-Thaga, omnye owasindayo. Kunye bakha ikhaya elincinci balibiza ngokuba yiRe-Nosi, okuthetha 'Sisodwa.' Babenakekelana kwaye behloniphana.",
        nso: "Kgale, tlhaselo e kgolo e ile ya phatlalatša batho ba Mhudi gomme ya senya motse wa gagwe. A nnoši lešokeng, Mhudi a kopana le Ra-Thaga, mophologi yo mongwe. Mmogo ba aga legae le lennyane ba le bitša Re-Nosi, e lego 'Re nnoši.' Ba be ba hlokomelana ba bile ba hlomphana.",
        st: "Kgale, tlhaselo e kgolo e ile ya qhalakanya batho ba Mhudi mme ya senya motse wa hae. A le mong lehwatateng, Mhudi a kopana le Ra-Thaga, mophonyohi e mong. Hammoho ba aha lehae le lenyane ba le bitsa Re-Nosi, ho bolelang 'Re le rong.' Ba ne ba hlokomelana mme ba hlomphana.",
        ss: "Endzabuko, kuhlasela lokukhulu kwahlakata bantfu bakaMhudi kwabhubhisa nelidolobha lakhe. Ayedvwa ehlane, Mhudi wahlangana naRa-Thaga, lomunye lowasindza. Ndzawonye bakha likhaya lelincane balibita ngeRe-Nosi, lokusho 'Sisodvwa.' Babenakekelana futsi bahloniphana.",
        ts: "Khale, nhlaselo lowukulu wu hangalase vanhu va Mhudi kutani wu onha muti wa yena. A ri yexe enhoveni, Mhudi u hlangana na Ra-Thaga, un'wana la poneke. Swin'we va aka kaya leritsongo va ri thya Re-Nosi, leswi vulaka 'Hi hi vote.' A va khathalelana naswona va xixavana.",
        nr: "Endulo, ukuhlasela okukhulu kwahlakaza abantu bakaMhudi kwatjhabalalisa nedorobho lakhe. Ayedwa ehlathini, uMhudi wahlangana noRa-Thaga, omunye owasindako. Ndawonye bakha ikhaya elincani balibiza ngoRe-Nosi, okutjho ukuthi 'Sisodwa.' Bebakhathalelana begodu bahloniphana.",
        ve: "Kale, nyanḓadzo khulu yo phaḓaladza vhathu vha Mhudi ya tshinyadza na muḓi wawe. E eṱhe sogani, Mhudi a ṱangana na Ra-Thaga, muṅwe muponyoki. Vhoṱhe vha fhaṱa hayani ṱhukhu vha ḽi vhidza Re-Nosi, zwine zwa amba 'Ri roṱhe.' Vho vha vha tshi ṱhogomelana nahone vha tshi ṱhonifhana.",
      },
    },
    "the-lion": {
      title: {
        af: "Mhudi en die Leeu",
        zu: "UMhudi Nengonyama",
        xh: "UMhudi Nengonyama",
        nso: "Mhudi le Tau",
        st: "Mhudi le Tau",
        ss: "Mhudi Nelibhubesi",
        ts: "Mhudi na Nghala",
        nr: "UMhudi Nesibhosi",
        ve: "Mhudi na Ndau",
      },
      text: {
        af: "In die wildernis het Mhudi haar as enigiemand se gelyke bewys. Toe 'n leeu hulle bedreig, was dit Mhudi wie se moed en vinnige oordeel vir Ra-Thaga gered het — een van verskeie oomblikke waarin Plaatje haar krag en agentskap uitbeeld en die koloniale stereotipe van Afrika-vroue as passief omverwerp.",
        zu: "Ehlane uMhudi wazibonakalisa elingana nanoma ubani. Lapho ingonyama ibasongela, kwakunguMhudi osibindi sakhe nokwahlulela okusheshayo kwasindisa uRa-Thaga — omunye wemizuzu eminingi lapho uPlaatje ebonisa amandla nokuzimela kwakhe, egumbuqela imibono yobandlululo yabesifazane base-Afrika njengabangenamandla.",
        xh: "Entlango uMhudi wazibonakalisa elingana naye nabani na. Xa ingonyama yabasongela, yayinguMhudi osibindi sakhe nokugweba ngokukhawuleza okwasindisa uRa-Thaga — omnye wemizuzwana emininzi apho uPlaatje ebonisa amandla nokuzimela kwakhe, ebhukuqa uluvo lobukoloniyali lokuba abafazi base-Afrika bangabangenzi nto.",
        nso: "Lešokeng Mhudi a itlhatsela e le wa go lekana le mang le mang. Ge tau e ba tšhošetša, e be e le Mhudi yo sebete sa gagwe le kahlolo ya gagwe ya lebelo di phološitšego Ra-Thaga — o mongwe wa metsotso e mentši moo Plaatje a bontšhago maatla le boikemelo bja gagwe, a menola kgopolo ya bokoloni ya gore basadi ba Afrika ke ba go se dire selo.",
        st: "Lehwatateng Mhudi a ipaka e le ea lekanang le mang kapa mang. Ha tau e ba tšosa, e ne e le Mhudi eo sebete sa hae le kahlolo ya hae e potlakileng di pholositseng Ra-Thaga — e mong oa metsotswana e mengata moo Plaatje a bontšang matla le boitaolo ba hae, a menola maikutlo a bokoloni a hore basali ba Afrika ke ba sa etseng letho.",
        ss: "Ehlane Mhudi watibonakalisa alingana nanoma ngubani. Nangabe libhubesi lababuka kabi, bekunguMhudi losibindzi sakhe nekwehlulela lokusheshako lokwasindzisa Ra-Thaga — lomunye weminyaka leminyenti lapho Plaatje akhombisa emandla nekutimela kwakhe, agumbucela imibono yebandlululo yebafati base-Afrika njengalabangenamandla.",
        ts: "Enhoveni Mhudi u tikombisa a ri la ringanaka na mani na mani. Loko nghala yi va chavisa, a ku ri Mhudi loyi vurhena bya yena ni ku avanyisa ka yena loku hatlisaka swi poniseke Ra-Thaga — un'wana wa timiniti to tala laha Plaatje a kombisaka matimba ni ku tiyimela ka yena, a hundzuluxa mavonelo ya vukoloni ya leswaku vavasati va Afrika i lava nga endliki nchumu.",
        nr: "Ehlathini uMhudi watibonakalisa alingana nanyana ngubani. Lokha isibhosi sibabuka kumbi, bekunguMhudi osibindi sakhe nokwahlulela okurhabako okwasindisa uRa-Thaga — omunye wemizuzu eminengi lapho uPlaatje atjengisa amandla nokuzijamela kwakhe, agumbuqela imibono yebandlululo yabafazi be-Afrika njengabanganamandla.",
        ve: "Sogani Mhudi a ḓisumbedza e wa u lingana na muṅwe na muṅwe. Musi ndau i tshi vha ofhisa, ho vha hu Mhudi we tshivhindi tshawe na khaṱhulo yawe ya u ṱavhanya zwa tshidza Ra-Thaga — muṅwe wa dzimineti nnzhi hune Plaatje a sumbedza maanḓa na u ḓiimisa hawe, a shandukisa muhumbulo wa vhukoloni wa uri vhafumakadzi vha Afrika ndi vha sa iti tshithu.",
      },
      childText: {
        af: "Op 'n dag het 'n leeu naby gekom. Mhudi was dapper en slim, en sy het vir Ra-Thaga van gevaar gered. In hierdie storie is Mhudi sterk en wys — 'n held.",
        zu: "Ngolunye usuku ingonyama yasondela. UMhudi wayenesibindi ehlakaniphile, wamsindisa uRa-Thaga engozini. Kule ndaba, uMhudi unamandla futhi uhlakaniphile — iqhawe.",
        xh: "Ngenye imini ingonyama yasondela. UMhudi wayenesibindi ekrelekrele, wamsindisa uRa-Thaga engozini. Kweli bali, uMhudi unamandla kwaye ulumkile — liqhawe.",
        nso: "Ka letšatši le lengwe tau ya batamela. Mhudi o be a e-na le sebete e bile a le bohlale, gomme a phološa Ra-Thaga kotsing. Kanegelong ye, Mhudi o na le maatla e bile o bohlale — mogale.",
        st: "Ka letsatsi le leng tau ya atamela. Mhudi o ne a e-na le sebete mme a le bohlale, mme a pholosa Ra-Thaga kotsing. Paleng ena, Mhudi o matla mme o bohlale — mohale.",
        ss: "Ngalelinye lilanga libhubesi lasondzela. Mhudi bekanesibindzi futsi ahlakaniphile, wamsindzisa Ra-Thaga engotini. Kulendzaba, Mhudi unemandla futsi uhlakaniphile — licawe.",
        ts: "Hi siku rin'wana nghala yi tshinela. Mhudi a a ri ni vurhena naswona a tlhariha, kutani a ponisa Ra-Thaga eku khombyeni. Eka ntsheketo lowu, Mhudi u ni matimba naswona wa tlhariha — nhenha.",
        nr: "Ngelinye ilanga isibhosi sasondela. UMhudi bekanesibindi begodu ahlakaniphile, wamsindisa uRa-Thaga engozini. Kule ndaba, uMhudi unamandla begodu uhlakaniphile — liqhawe.",
        ve: "Nga ḽiṅwe ḓuvha ndau ya sendela. Mhudi o vha e na tshivhindi nahone o ṱalifha, a tshidza Ra-Thaga khomboni. Kha tshiitwa itshi, Mhudi u na maanḓa nahone o ṱalifha — muhali.",
      },
    },
  },

  "ityala-lamawele": {
    "the-lawsuit": {
      title: {
        af: "Die Regsgeding van die Tweeling",
        zu: "Icala Lamawele",
        xh: "Ityala Lamawele",
        nso: "Tsheko ya Mawele",
        st: "Nyewe ya Mafahla",
        ss: "Licala Lemawele",
        ts: "Nandzu wa Mahasa",
        nr: "Icala Lamawele",
        ve: "Mulandu wa Mafhasi",
      },
      text: {
        af: "In die tyd van koning Hintsa het twee tweelingbroers — Wele en Babini — voor die inkundla, die tradisionele Xhosa-hof, verskyn. Hul vader het gesterf, en omdat hulle op dieselfde dag gebore is, kon nie een van hulle sommer die senioriteit opeis wat erfenis en opvolging bepaal het nie. Hul geskil sou die wysheid van umthetho (die wet) en sy strewe na ubulungisa (geregtigheid) toets.",
        zu: "Ngesikhathi seNkosi uHintsa, abafowabo abangamawele ababili — uWele noBabini — beza phambi kwenkundla, inkantolo yendabuko yamaXhosa. Uyise wayeshonile, futhi ngenxa yokuthi bazalwa ngosuku olulodwa, akekho phakathi kwabo owayengavele athi ubudala obabunquma ifa nokulandelana. Ukungqubuzana kwabo kwakuzovivinya ukuhlakanipha kuka-umthetho nokufuna kwawo u-ubulungisa.",
        xh: "Ngexesha likaKumkani uHintsa, abazalwana abangamawele ababini — uWele noBabini — beza phambi kwenkundla, inkundla yesintu yamaXhosa. Uyise wayefile, kwaye ngenxa yokuba bazalwa ngamini nye, akakho kubo owayenokuvele afune ubudala obabusenza ilifa nokulandelelana. Impikiswano yabo yayiza kuvavanya ubulumko buka-umthetho nokufuna kwawo u-ubulungisa.",
        nso: "Mehleng ya Kgoši Hintsa, banababo ba babedi ba mawele — Wele le Babini — ba tla pele ga inkundla, kgorotsheko ya setšo ya Xhosa. Tatago bona o be a hwile, gomme ka ge ba belegwe ka letšatši le tee, ga go yo a bego a ka ipolela bogolo bjo bo bego bo laola bohwa le go latelana. Kganetšano ya bona e be e tla leka bohlale bja umthetho le tabapelo ya wona ya ubulungisa.",
        st: "Mehleng ya Morena Hintsa, baena ba babeli ba mafahla — Wele le Babini — ba tla pela ho inkundla, lekgotla la moetlo la Xhosa. Ntataʼbona o ne a shwele, mme kaha ba tsoetsoe ka letsatsi le le leng, ha ho ea neng a ka ipolela boholo bo neng bo laola lefa le ho hlahlamana. Qabang ya bona e ne e tla leka bohlale ba umthetho le takatso ya oona ya ubulungisa.",
        ss: "Ngesikhatsi seNkhosi Hintsa, bomnakabo lababili labamawele — Wele naBabini — beta embikwenkundla, inkantolo yesintfu yemaXhosa. Uyise abesashonile, futsi ngenca yekutsi batalwa ngelilanga linye, akekho emkhatsini wabo lobengavele atsi budzala lobebunquma lifa nekulandzelana. Kungcubutana kwabo bekutawuvivinya kuhlakanipha kwe-umthetho nekufuna kwawo i-ubulungisa.",
        ts: "Enkarhini wa Hosi Hintsa, vamakwavo vambirhi va mahasa — Wele na Babini — va ta emahlweni ka inkundla, huvo ya ndhavuko ya Xhosa. Tata wa vona a a file, naswona hikwalaho ka leswi va velekiweke hi siku rin'we, a ku na loyi a nga ta vula vukulukumba lebyi a byi lawula ndzhaka ni ku landzelelana. Ku kanetana ka vona a ku ta ringeta vutlhari bya umthetho ni ku lava ka byona ubulungisa.",
        nr: "Ngesikhathi seKosi uHintsa, abafowabo ababili abamawele — uWele noBabini — beza phambi kwenkundla, ikhotho yesintu yamaXhosa. Uyise bekahlongakele, begodu ngebanga lokobana babelethwa ngelanga linye, akekho hlangana nabo obekangavele athi budala obebunquma ifa nokulandelana. Ukurholana kwabo bekuzokuvivinya ukuhlakanipha kwe-umthetho nokufuna kwawo i-ubulungisa.",
        ve: "Nga tshifhinga tsha Khosi Hintsa, vharathu vhavhili vha mafhasi — Wele na Babini — vha ḓa phanḓa ha inkundla, khoro ya sialala ya Xhosa. Khotsi avho o vha o fa, nahone samusi vho bebwa nga ḓuvha ḽithihi, a hu na we a nga amba vhuhulwane he ha vha ha langa ifa na u tevhekana. Khani yavho yo vha i tshi ḓo linga vhuṱali ha umthetho na u ṱoḓa hawo ubulungisa.",
      },
      childText: {
        af: "Lank gelede het tweelingbroers met die name Wele en Babini 'n probleem gehad. Hul vader het gesterf, en omdat hulle op dieselfde dag gebore is, het niemand geweet watter broer die oudste is nie. So het hulle na die inkundla — die volkshof — gegaan om 'n regverdige antwoord te vind.",
        zu: "Endulo, abafowabo abangamawele ababizwa ngoWele noBabini babenenkinga. Uyise wayeshonile, futhi ngenxa yokuthi bazalwa ngosuku olulodwa, akekho owayazi ukuthi imuphi umfowabo omdala. Ngakho baya enkundleni — inkantolo yabantu — ukuze bathole impendulo enobulungiswa.",
        xh: "Kudala, abazalwana abangamawele ababizwa ngoWele noBabini babenengxaki. Uyise wayefile, kwaye ngenxa yokuba bazalwa ngamini nye, akakho owayesazi ukuba nguwuphi umzalwana omdala. Ngoko baya enkundleni — inkundla yabantu — ukuze bafumane impendulo enobulungisa.",
        nso: "Kgale, banababo ba mawele bao ba bitšwago Wele le Babini ba be ba na le bothata. Tatago bona o be a hwile, gomme ka ge ba belegwe ka letšatši le tee, ga go yo a bego a tseba gore ke ofe wa bona yo mogolo. Ka gona ba ya inkundla — kgorotsheko ya batho — go hwetša karabo ye e lokilego.",
        st: "Kgale, baena ba mafahla ba bitsoang Wele le Babini ba ne ba e-na le bothata. Ntataʼbona o ne a shwele, mme kaha ba tsoetsoe ka letsatsi le le leng, ha ho ea neng a tseba hore na ke ofe ea moholo. Kahoo ba ya inkundla — lekgotla la batho — ho fumana karabo e nepahetseng.",
        ss: "Endzabuko, bomnakabo labamawele lababitwa ngoWele naBabini bebanenkinga. Uyise abesashonile, futsi ngenca yekutsi batalwa ngelilanga linye, akekho lobekati kutsi ngumuphi umnakabo lomdzala. Ngako baya enkundleni — inkantolo yebantfu — kuze batfole imphendvulo lenebulungisa.",
        ts: "Khale, vamakwavo va mahasa lava vuriwaka Wele na Babini a va ri ni xiphiqo. Tata wa vona a a file, naswona hikwalaho ka leswi va velekiweke hi siku rin'we, a ku na loyi a a tiva leswaku i wihi makwavo lonkulu. Hikwalaho va ya eka inkundla — huvo ya vanhu — ku kuma nhlamulo leyi lulameke.",
        nr: "Endulo, abafowabo abamawele ababizwa ngoWele noBabini bebanobudisi. Uyise bekahlongakele, begodu ngebanga lokobana babelethwa ngelanga linye, akekho obekazi bona ngimuphi umfowabo omdala. Ngalokho baya enkundleni — ikhotho yabantu — bona bathole ipendulo enobulungisa.",
        ve: "Kale, vharathu vha mafhasi vhane vha pfi Wele na Babini vho vha vha na thaidzo. Khotsi avho o vha o fa, nahone samusi vho bebwa nga ḓuvha ḽithihi, a hu na we a ḓivha uri ndi ufhio murathu muhulwane. Ngauralo vha ya inkundla — khoro ya vhathu — u wana phindulo yo lugaho.",
      },
    },
    "wisdom-of-the-inkundla": {
      title: {
        af: "Die Wysheid van die Inkundla",
        zu: "Ukuhlakanipha Kwenkundla",
        xh: "Ubulumko Benkundla",
        nso: "Bohlale bja Inkundla",
        st: "Bohlale ba Inkundla",
        ss: "Kuhlakanipha Kwenkundla",
        ts: "Vutlhari bya Inkundla",
        nr: "Ukuhlakanipha Kwenkundla",
        ve: "Vhuṱali ha Inkundla",
      },
      text: {
        af: "Die inkundla het nie gehaas nie. Raadslede het getuienis opgeweeg en kruisondervra; die vroedvroue is geroep om te getuig oor die gebruik wat die tweede-gebore by geboorte gemerk het. Stap vir stap het die hof na die waarheid geredeneer. Uiteindelik het die broers hulself verneder, elkeen het die ander se senioriteit geëer — want in die Xhosa-reg was die doel nie een broer se oorwinning nie, maar die herstel van harmonie tussen hulle. Dit is herstellende geregtigheid: ubulungisa wat die gemeenskap genees.",
        zu: "Inkundla ayizange isheshe. Amakhansela akala ubufakazi futhi abuza imibuzo enzima; ababelethisi babizwa ukuba bafakaze ngesiko elaliphawule owesibili ozelwe ngesikhathi ezalwa. Isinyathelo nesinyathelo inkantolo yacabanga iya eqinisweni. Ekugcineni abafowabo bazithoba, ngamunye ehlonipha ubudala bomunye — ngoba emthethweni wesiXhosa inhloso yayingekona ukunqoba komunye umfowabo kodwa ukubuyisela ukuzwana phakathi kwabo. Lokhu ubulungisa obelaphayo umphakathi.",
        xh: "Inkundla ayizange ingxame. Amaphakathi akala ubungqina aza abuza imibuzo enzima; ababelekisi babizwa ukuba bangqine ngesiko elaliphawule owesibini ozelweyo ekuzalweni. Inyathelo nenyathelo inkundla yaqiqa isiya enyanisweni. Ekugqibeleni abazalwana bazithoba, ngamnye ehlonipha ubudala bomnye — kuba kumthetho wamaXhosa injongo yayingekhona uloyiso lomnye umzalwana koko ukubuyisela uxolo phakathi kwabo. Obu bubulungisa obuphilisa uluntu.",
        nso: "Inkundla ga se ya ka ya kitima. Bakgomana ba lekola bohlatse gomme ba botšiša dipotšišo tše thata; babelegiši ba bitšwa go hlatsela ka setšo se se bego se swaile wa bobedi yo a belegwego ge a belegwa. Kgato ka kgato kgorotsheko ya nagana e lebile therešong. Mafelelong banababo ba ikokobetša, yo mongwe le yo mongwe a hlompha bogolo bja yo mongwe — gobane molaong wa Xhosa maikemišetšo e be e se phenyo ya monwananoši eupša go bušetša kwano gare ga bona. Ye ke tshwaro ya go fodiša: ubulungisa bjo bo fodišago setšhaba.",
        st: "Inkundla ha e a ka ya potlaka. Bakgomana ba lekola bopaki mme ba botsa lipotso tse thata; babelehisi ba bitsoa ho paka ka moetlo o neng o tšoaile oa bobeli ea tsoetsoeng ha a tsoaloa. Mohato ka mohato lekgotla la nahana le lebile ʼneteng. Qetellong baena ba ikokobetsa, e mong le e mong a hlompha boholo ba e mong — hobane molaong oa Xhosa morero e ne e se tlhōlō ya e mong oa baena empa ho khutlisa kutloano pakeng tsa bona. Ena ke toka e folisang: ubulungisa bo folisang setjhaba.",
        ss: "Inkundla ayizange isheshe. Emakhansela akala bufakazi futsi abuta imibuto lelukhuni; bomabeletsisi babitwa kutsi bafakaze ngelisiko lelaliphawule wesibili lotelwe nasatelwa. Sinyatselo nesinyatselo inkantolo yacabanga iya eciniso. Ekugcineni bomnakabo batitsoba, ngamunye ahlonipha budzala balomunye — ngobe emtsetfweni wesiXhosa inhloso beyingasiko kunqoba kwalomunye umnakabo kodvwa kubuyisela kuzwana emkhatsini wabo. Loku yibulungisa lelaphako umphakatsi.",
        ts: "Inkundla a yi hatlisanga. Valuv eti va kala vumbhoni naswona va vutisa swivutiso swo tika; vabelekisi va vitaniwa ku va va vumbhoni hi ndhavuko lowu a wu funge la velekiweke wa vumbirhi loko a velekiwa. Goza hi goza huvo yi anakanya yi kongoma entiyisweni. Eku heteleleni vamakwavo va titsongahata, un'wana ni un'wana a xixima vukulukumba bya un'wana — hikuva eka nawu wa Xhosa xikongomelo a xi nga ri ku hlula ka un'wana wa vamakwavo kambe ku vuyisela ku twanana exikarhi ka vona. Leyi i vululami lebyi horisaka: ubulungisa lebyi horisaka vaaki.",
        nr: "Inkundla ayikhange irhabe. Amakhansela akala ubufakazi begodu abuza imibuzo ebudisi; ababelethisi babizwa bona bafakaze ngesiko elaphawula owesibili obelethwako nakabelethwako. Igadango negadango ikhotho yacabanga iya eqinisweni. Ekugcineni abafowabo batitloba, ngamunye ahlonipha ubudala bomunye — ngombana emthethweni wamaXhosa umnqopho bewungasi kuhlula komunye umfowabo kodwana ukubuyisela ukuzwana hlangana nabo. Lokhu yibulungisa elilaphako umphakathi.",
        ve: "Inkundla a yo ngo ṱavhanya. Vhakoma vha ela vhuṱanzi nahone vha vhudzisa mbudziso khaladzi; vhabebisi vha vhidzwa u ṱanziela nga sialala ḽe ḽa swaya wa vhuvhili we a bebwa musi a tshi bebwa. Ganḓa nga ganḓa khoro ya humbula i tshi livha ngohoni. Mafheleloni vharathu vha ḓiṱukufhadza, muṅwe na muṅwe a tshi ṱhonifha vhuhulwane ha muṅwe — ngauri kha mulayo wa Xhosa ndivho yo vha i si u kunda ha muṅwe murathu fhedzi u vhuyedzedza u pfana vhukati havho. Hoyu ndi vhululami vhu fholisaho: ubulungisa vhu fholisaho tshitshavha.",
      },
      childText: {
        af: "Die hof het aandagtig geluister. Wyse raadslede het vrae gevra, en die vroedvroue wat by die tweeling se geboorte was, het vertel wat hulle onthou het. Stadig het die waarheid duidelik geword. Uiteindelik het elke broer gekies om die ander te eer. Die hof wou nie 'n wenner en 'n verloorder hê nie — dit wou vrede tussen die broers en hul familie hê.",
        zu: "Inkantolo yalalela ngokucophelela. Amakhansela ahlakaniphile abuza imibuzo, futhi ababelethisi ababekhona ngesikhathi kuzalwa amawele baxoxa lokho abakukhumbulayo. Kancane iqiniso lacaca. Ekugcineni umfowabo ngamunye wakhetha ukuhlonipha omunye. Inkantolo yayingafuni onqobayo nolahlekelwayo — yayifuna ukuthula phakathi kwabafowabo nomndeni wabo.",
        xh: "Inkundla yaphulaphula ngocoselelo. Amaphakathi obulumko abuza imibuzo, kwaye ababelekisi ababekho ngexesha kuzalwa amawele babalisa oko bakukhumbulayo. Kancinci inyaniso yacaca. Ekugqibeleni umzalwana ngamnye wakhetha ukuhlonipha omnye. Inkundla yayingafuni ophumeleleyo notshabeleyo — yayifuna uxolo phakathi kwabazalwana nosapho lwabo.",
        nso: "Kgorotsheko ya theeletša ka šedi. Bakgomana ba bohlale ba botšiša dipotšišo, gomme babelegiši bao ba bego ba le gona ge mawele a belegwa ba anega seo ba se gopolago. Gannyane therešo ya hlaka. Mafelelong ngwana yo mongwe le yo mongwe a kgetha go hlompha yo mongwe. Kgorotsheko ga se ya nyaka mofenyi le mofenywa — e be e nyaka khutšo gare ga banababo le lapa la bona.",
        st: "Lekgotla la mamela ka hloko. Bakgomana ba bohlale ba botsa lipotso, mme babelehisi ba neng ba le teng ha mafahla a tsoaloa ba pheta seo ba se hopolang. Butle ʼnete ya hlaka. Qetellong ngoana e mong le e mong a kgetha ho hlompha e mong. Lekgotla ha le a ka la batla mohlodi le mohlolehi — le ne le batla kgotso pakeng tsa baena le lelapa la bona.",
        ss: "Inkantolo yalalela ngekucophelela. Emakhansela lahlakaniphile abuta imibuto, futsi bomabeletsisi labebakhona nakutalwa emawele baxoxa loko labakukhumbulako. Kancane liciniso lacaca. Ekugcineni umnakabo ngamunye wakhetsa kuhlonipha lomunye. Inkantolo beyingafuni lonqobako nalahlulekako — beyifuna kuthula emkhatsini wabomnakabo nemndeni wabo.",
        ts: "Huvo yi yingisela hi vukheta. Valuvutii va vutlhari va vutisa swivutiso, naswona vabelekisi lava a va ri kona loko mahasa ma velekiwa va rungula leswi va swi tsundzukaka. Kutsongo ntiyiso wu twala. Eku heteleleni makwavo un'wana ni un'wana u hlawula ku xixima un'wana. Huvo a yi lavanga muhluri ni mulahlekeriwa — a yi lava ku rhula exikarhi ka vamakwavo ni ndyangu wa vona.",
        nr: "Ikhotho yalalela ngokutjheja. Amakhansela ahlakaniphileko abuza imibuzo, begodu ababelethisi ebebakhona nakubelethwa amawele baxoxa lokho abakukhumbulako. Kancani iqiniso lacaca. Ekugcineni umfowabo ngamunye wakhetha ukuhlonipha omunye. Ikhotho beyingafuni onqobako nolahlekelwako — beyifuna ukuthula hlangana nabafowabo nomndeni wabo.",
        ve: "Khoro ya thetshelesa nga vhukhwaṱhi. Vhakoma vha vhuṱali vha vhudzisa mbudziso, nahone vhabebisi vhe vha vha vhe hone musi mafhasi a tshi bebwa vha anetshela zwe vha zwi humbula. Zwiṱuku ngoho ya vha khagala. Mafheleloni murathu muṅwe na muṅwe a nanga u ṱhonifha muṅwe. Khoro a yo ngo ṱoḓa mukundi na mukundwa — yo vha i tshi ṱoḓa mulalo vhukati ha vharathu na muṱa wavho.",
      },
    },
  },

  indaba: {
    "ninavanhu-ma": {
      title: {
        af: "Ninavanhu-Ma, die Groot Moeder",
        zu: "UNinavanhu-Ma, uMame Omkhulu",
        xh: "UNinavanhu-Ma, uMama Omkhulu",
        nso: "Ninavanhu-Ma, Mmagolo",
        st: "Ninavanhu-Ma, ʼMe e Moholo",
        ss: "Ninavanhu-Ma, Make Lomkhulu",
        ts: "Ninavanhu-Ma, Manana Lonkulu",
        nr: "UNinavanhu-Ma, uMma Omkhulu",
        ve: "Ninavanhu-Ma, Mme Muhulu",
      },
      text: {
        af: "Indaba, my kinders. So begin Credo Mutwa se vertelling van die ou skeppingsverhaal. In die begin, vertel hy, het Ninavanhu-Ma — die Groot Moeder — gekom, en die Boom van die Lewe waaruit die volke van die aarde sou voortspruit. Mutwa, 'n Zoeloe-sanusi, het hierdie mondelinge oorlewerings in 1964 neergeskryf en 'n bewaarder se eed van geheimhouding verbreek omdat hy gevrees het dat hulle onder kolonialisme en apartheid vir altyd verlore mag gaan.",
        zu: "Indaba, bantwana bami. Kuqala kanjalo ukulanda kukaCredo Mutwa kwendaba yendala yendalo. Ekuqaleni, uyalanda, kwafika uNinavanhu-Ma — uMame Omkhulu — noMuthi Wokuphila okwaphuma kuwo izizwe zomhlaba. UMutwa, isanusi lesiZulu, wazibhala phansi lezi zinganekwane zomlomo ngo-1964, ephula isifungo somgcini sokugcina imfihlo ngoba wayesaba ukuthi ngaphansi kobukoloni nobandlululo zingalahleka phakade.",
        xh: "Indaba, bantwana bam. Kuqala ngolo hlobo ukubalisa kukaCredo Mutwa kwebali lokudala eladala. Ekuqaleni, uyabalisa, kwafika uNinavanhu-Ma — uMama Omkhulu — noMthi Wobomi apho zaphuma khona izizwe zomhlaba. UMutwa, isanusi lamaZulu, wazibhala phantsi ezi zithethe zomlomo ngo-1964, esaphula isifungo somgcini sokugcina imfihlo kuba wayesoyika ukuba phantsi kobukoloniyali nocalucalulo zinokulahleka ngonaphakade.",
        nso: "Indaba, bana ba ka. Ka mokgwa woo Credo Mutwa a thomago kanegelo ya kgale ya tlholego. Mathomong, o a anega, gwa tla Ninavanhu-Ma — Mmagolo — le Sehlare sa Bophelo seo merafe ya lefase e bego e tla tšwa go sona. Mutwa, sanusi wa Muzulu, o ngwadile ditšo tše tša molomo ka 1964, a roba keno ya mohlokomedi ya go boloka sephiri ka gobane a be a boifa gore ka tlase ga bokoloni le kgethollo di ka lahlega go ya go ile.",
        st: "Indaba, bana ba ka. Ke kamoo Credo Mutwa a qalang kateng pale ya kgale ya pōpo. Qalong, oa pheta, ha tla Ninavanhu-Ma — ʼMe e Moholo — le Sefate sa Bophelo seo merabe ya lefatshe e neng e tla tsoa ho sona. Mutwa, sanusi oa Mozulu, o ngotse litšo tsena tsa molomo ka 1964, a roba kano ya mohlokomeli ya ho boloka lekunutu hobane o ne a tšaba hore tlas'a bokoloni le kgethollo li ka lahleha ka ho sa feleng.",
        ss: "Indaba, bantfwana bami. Kucala kanjalo kulandza kwaCredo Mutwa kwendzaba lendzala yekudala. Ekucaleni, uyalandza, kwefika Ninavanhu-Ma — Make Lomkhulu — neSihlahla Sekuphila lokwaphuma kuso tive temhlaba. Mutwa, sanusi lesiZulu, wabhala phansi letinganekwane temlomo nga-1964, ephula sifungo semgcini sekugcina imfihlo ngobe abesaba kutsi ngaphansi kwebukoloni nebandlululo tingalahleka phakadze.",
        ts: "Indaba, vana va mina. Hi ndlela leyi Credo Mutwa a sungulaka ku rungula ka yena ntsheketo wa khale wa ntumbuluko. Eku sunguleni, wa rungula, ku fika Ninavanhu-Ma — Manana Lonkulu — ni Murhi wa Vutomi laha ku humaka tinxaka ta misava. Mutwa, sanusi wa Muzulu, u tsale mikhuva leyi ya nomu hi 1964, a tshova xihlambanyo xa muhlayisi xa ku hlayisa xihundla hikuva a a chava leswaku ehansi ka vukoloni ni xihlawuhlawu yi nga lahleka hi masiku.",
        nr: "Indaba, bantwana bami. Kuthoma kunjalo ukurhatjha kukaCredo Mutwa kwendaba endala yokudala. Ekuthomeni, uyarhatjha, kwafika uNinavanhu-Ma — uMma Omkhulu — noMuthi Wokuphila okwaphuma kuwo iintjhaba zephasi. UMutwa, isanusi lesiZulu, watlola phasi iindatjhana zomlomo nga-1964, ephula isifungo somgcini sokugcina imfihlo ngombana bekasaba bona ngaphasi kobukoloni nobandlululo zingalahleka bhoke.",
        ve: "Indaba, vhana vhanga. Ndi nga nḓila iyi Credo Mutwa a thomaho u anetshela hawe tshiitwa tsha kale tsha tsiko. Mathomoni, u a anetshela, ha ḓa Ninavanhu-Ma — Mme Muhulu — na Muri wa Vhutshilo hune tshaka dza shango dza bva khao. Mutwa, sanusi wa Muzulu, o ṅwala mikhuva iyi ya mulomo nga 1964, a tshi thutha muано wa muvhulungi wa u vhulunga tshiphiri ngauri o vha a tshi ofha uri fhasi ha vhukoloni na khethululo dzi nga xela nga hu sa fheli.",
      },
      childText: {
        af: "'Indaba, my kinders' beteken 'Ek het 'n storie vir julle, my kinders.' So het Credo Mutwa die baie ou storie begin van hoe die wêreld gemaak is. Hy het vertel van Ninavanhu-Ma, die Groot Moeder, en die Boom van die Lewe waaruit alle volke gekom het. Mutwa het hierdie stories neergeskryf sodat hulle nooit vergeet sou word nie.",
        zu: "'Indaba, bantwana bami' kusho ukuthi 'Nginendaba yenu, bantwana bami.' Yindlela uCredo Mutwa aqala ngayo indaba endala kakhulu yokuthi umhlaba wenziwa kanjani. Wakhuluma ngoNinavanhu-Ma, uMame Omkhulu, noMuthi Wokuphila okwaphuma kuwo bonke abantu. UMutwa wazibhala phansi lezi zindaba ukuze zingalokothi zikhohlakale.",
        xh: "'Indaba, bantwana bam' kuthetha ukuthi 'Ndinebali kuni, bantwana bam.' Yindlela uCredo Mutwa awaqala ngayo ibali elidala kakhulu lokuba umhlaba wenziwa njani. Wathetha ngoNinavanhu-Ma, uMama Omkhulu, noMthi Wobomi apho baphuma khona bonke abantu. UMutwa wazibhala phantsi ezi zibali ukuze zingaze zilibaleke.",
        nso: "'Indaba, bana ba ka' e ra gore 'Ke na le kanegelo ya lena, bana ba ka.' Ke kamoo Credo Mutwa a thomilego kanegelo ye kgologolo ya gore lefase le hlodilwe bjang. O boletše ka Ninavanhu-Ma, Mmagolo, le Sehlare sa Bophelo seo batho ka moka ba tšwago go sona. Mutwa o ngwadile dikanegelo tše gore di se ke tša lebalwa.",
        st: "'Indaba, bana ba ka' e bolela 'Ke na le pale ya lona, bana ba ka.' Ke kamoo Credo Mutwa a qalileng pale e kgolo haholo ya hore lefatshe le entsoe joang. O buile ka Ninavanhu-Ma, ʼMe e Moholo, le Sefate sa Bophelo seo batho bohle ba tsoang ho sona. Mutwa o ngotse lipale tsena e le hore li se ke tsa lebaloa.",
        ss: "'Indaba, bantfwana bami' isho kutsi 'Nginendzaba yenu, bantfwana bami.' Yindlela Credo Mutwa lacala ngayo indzaba lendzala kakhulu yekutsi umhlaba wentiwa njani. Wakhuluma ngoNinavanhu-Ma, Make Lomkhulu, neSihlahla Sekuphila lokwaphuma kuso bonkhe bantfu. Mutwa wabhala phansi letindzaba kuze tingaze tikhohlakale.",
        ts: "'Indaba, vana va mina' swi vula 'Ndzi ni ntsheketo wa n'wina, vana va mina.' Hi ndlela leyi Credo Mutwa a sunguleke ntsheketo wo khaleha swinene wa leswaku misava yi endliwe njhani. U vulavule hi Ninavanhu-Ma, Manana Lonkulu, ni Murhi wa Vutomi laha ku humaka vanhu hinkwavo. Mutwa u tsale mintsheketo leyi leswaku yi nga tshuki yi rivariwa.",
        nr: "'Indaba, bantwana bami' kutjho ukuthi 'Nginendaba yenu, bantwana bami.' Yindlela uCredo Mutwa athoma ngayo indaba endala khulu yokuthi iphasi lenziwa njani. Wakhuluma ngoNinavanhu-Ma, uMma Omkhulu, noMuthi Wokuphila okwaphuma kuwo boke abantu. UMutwa watlola phasi iindaba lezi bona zingalibaleki.",
        ve: "'Indaba, vhana vhanga' zwi amba 'Ndi na tshiitwa tshaṋu, vhana vhanga.' Ndi nḓila ye Credo Mutwa a thoma ngayo tshiitwa tsha kale vhukuma tsha uri shango ḽo sikwa hani. O amba nga Ninavanhu-Ma, Mme Muhulu, na Muri wa Vhutshilo hune vhathu vhoṱhe vha bva khao. Mutwa o ṅwala zwiitwa izwi uri zwi si vhuye zwa hangwiwa.",
      },
    },
    "keeping-the-story-alive": {
      title: {
        af: "Om die Verhaal Lewend te Hou",
        zu: "Ukugcina Indaba Iphila",
        xh: "Ukugcina Ibali Liphila",
        nso: "Go Boloka Kanegelo e Phela",
        st: "Ho Boloka Pale e Phela",
        ss: "Kugcina Indzaba Iphila",
        ts: "Ku Hlayisa Ntsheketo wu Hanya",
        nr: "Ukugcina Indaba Iphila",
        ve: "U Vhulunga Tshiitwa Tshi Tshila",
      },
      text: {
        af: "Benewens die skeppingsmite dra Indaba, My Children die trekke van die Bantu-sprekende volke, die kodes van krygers, en die rites wat die groot oorgange van die lewe gemerk het. Mutwa het nie hierdie geskiedenis gesuiwer nie — hy het die swaarkry naas die skoonheid opgeteken. Om hom te lees is om 'n kosmologie te erf, en 'n waarskuwing oor wat verlore gaan wanneer 'n volk se verhale onbewaar bly.",
        zu: "Ngaphandle kwenganekwane yendalo, Indaba, My Children iphethe ukufuduka kwabantu abakhuluma isiBantu, imithetho yamabutho, kanye nemikhosi eyayiphawula iziqephu ezinkulu zokuphila. UMutwa akazange ayihlanze le mlando — wabhala ubunzima kanye nobuhle. Ukumfunda kusho ukuzuza ifa lekhosmoloji, nesixwayiso ngalokho okulahlekayo lapho izindaba zabantu zingagcinwa.",
        xh: "Ngaphandle kwentsomi yokudala, Indaba, My Children iphethe ukufuduka kwabantu abathetha isiBantu, imithetho yamajoni, kunye nemibhiyozo eyayiphawula iziqendu ezinkulu zobomi. UMutwa akazange ayicoce le mbali — wabhala ubunzima kunye nobuhle. Ukumfunda kukuzuza ikhosmoloji, nesilumkiso ngoko kulahlekayo xa amabali abantu engagcinwa.",
        nso: "Ntle le nonwane ya tlholego, Indaba, My Children e swere mafudišo a merafe ya go bolela Sebantu, melao ya bahlabani, le meletlo yeo e bego e swaya dikgato tše kgolo tša bophelo. Mutwa ga se a hlwekiša histori ye — o ngwadile mathata gotee le botse. Go mmala ke go rua khosmoloji, le temošo ka seo se lahlegago ge dikanegelo tša setšhaba di sa bolokwe.",
        st: "Ntle le tšomo ya pōpo, Indaba, My Children e tšoere ho falla ha merabe e buang Sebantu, melao ea bahlabani, le meketjana e neng e tšoaea likarolo tse kgolo tsa bophelo. Mutwa ha a ka a hloekisa histori ena — o ngotse mathata hammoho le botle. Ho mmala ke ho rua khosmoloji, le temoso ka se lahlehang ha lipale tsa setjhaba li sa bolokoe.",
        ss: "Ngaphandle kwenganekwane yekudala, Indaba, My Children iphetse kufudvuka kwebantfu labakhuluma siBantu, imitsetfo yemabutfo, kanye nemikhosi lebeyiphawula tigaba letinkhulu tekuphila. Mutwa akazange ayihlante lomlandvo — wabhala bunzima kanye nebuhle. Kumfundza kusho kutfola lifa lekhosmoloji, nesexwayiso ngaloko lokulahlekako nangabe tindzaba tebantfu tingagcinwa.",
        ts: "Handle ka ntsheketo wa ntumbuluko, Indaba, My Children yi khoma ku rhurha ka vanhu lava vulavulaka Xibantu, milawu ya masocha, ni minkhuvo leyi a yi funga swiphemu leswikulu swa vutomi. Mutwa a nga tenganga matimu lawa — u tsale maxangu swin'we ni ku saseka. Ku n'wi hlaya i ku amukela khosmoloji, ni xitsundzuxo hi leswi lahlekaka loko mintsheketo ya vanhu yi nga hlayisiwi.",
        nr: "Ngaphandle kwenganekwane yokudala, Indaba, My Children iphethe ukufuduka kwabantu abakhuluma isiBantu, imithetho yamabutho, kanye nemikhosi ebeyiphawula iingcenye ezikhulu zokuphila. UMutwa akhange ayihlanze umlando lo — watlola ubudisi kanye nobuhle. Ukumfunda kutjho ukuzuza ilifa lekhosmoloji, nesiyeleliso ngalokho okulahlekako nakungagcinwa iindaba zabantu.",
        ve: "Nntha ha ngano ya tsiko, Indaba, My Children i fara u pfuluwa ha vhathu vha ambaho Tshibantu, milayo ya maswole, na mikosi ye ya vha i tshi swaya masia mahulu a vhutshilo. Mutwa a songo kunakisa ḓivhazwakale iyi — o ṅwala vhuleme khathihi na vhulenda. U mu vhala ndi u ṱanganedza khosmoloji, na tsevho nga zwine zwa xela musi zwiitwa zwa tshitshavha zwi sa vhulungwi.",
      },
      childText: {
        af: "Credo Mutwa se boek hou baie stories in — van lang reise, van dapper krygers, en van die spesiale seremonies wat grootword gemerk het. Hy het die hele waarheid vertel, die moeilike dele en die mooi dele. Sy stories herinner ons waarom dit saak maak om ons geskiedenis lewend te hou.",
        zu: "Incwadi kaCredo Mutwa iphethe izindaba eziningi — zohambo olude, zamabutho anesibindi, kanye nemicimbi ekhethekile eyayiphawula ukukhula. Wakhuluma iqiniso lonke, izingxenye ezinzima nezingxenye ezinhle. Izindaba zakhe zisikhumbuza ukuthi kungani kubalulekile ukugcina umlando wethu uphila.",
        xh: "Incwadi kaCredo Mutwa iphethe amabali amaninzi — ohambo olude, amajoni anesibindi, kunye nemibhiyozo ekhethekileyo eyayiphawula ukukhula. Wathetha inyaniso yonke, iindawo ezinzima neendawo ezintle. Amabali akhe asikhumbuza ukuba kutheni kubalulekile ukugcina imbali yethu iphila.",
        nso: "Puku ya Credo Mutwa e na le dikanegelo tše dintši — tša maeto a matelele, tša bahlabani ba sebete, le meletlo ye e kgethegilego yeo e bego e swaya go gola. O boletše therešo ka moka, dikarolo tše thata le tše botse. Dikanegelo tša gagwe di re gopotša gore ke ka lebaka la eng go le bohlokwa go boloka histori ya rena e phela.",
        st: "Buka ya Credo Mutwa e na le lipale tse ngata — tsa maeto a malelele, tsa bahlabani ba sebete, le meketjana e kgethehileng e neng e tšoaea ho hola. O buile ʼnete eohle, likarolo tse thata le tse ntle. Lipale tsa hae li re hopotsa hore na ke hobaneng ho le bohlokwa ho boloka histori ya rona e phela.",
        ss: "Incwadzi yaCredo Mutwa iphetse tindzaba letinyenti — tekuhamba lokudze, temabutfo lanesibindzi, kanye nemicimbi lekhetsekile lebeyiphawula kukhula. Wakhuluma liciniso lonkhe, tigaba letilukhuni netigaba letinhle. Tindzaba takhe tisikhumbuta kutsi kungani kubalulekile kugcina umlandvo wetfu uphila.",
        ts: "Buku ya Credo Mutwa yi ni mintsheketo yo tala — ya maendzo yo leha, ya masocha lama nga ni vurhena, ni minkhuvo yo hlawuleka leyi a yi funga ku kula. U vulavule ntiyiso hinkwawo, swiphemu leswi tikaka ni leswi sasekaka. Mintsheketo ya yena yi hi tsundzuxa leswaku ha yini swi ri swa nkoka ku hlayisa matimu ya hina ma hanya.",
        nr: "Incwadi kaCredo Mutwa iphethe iindaba ezinengi — zekhambo elide, zamabutho anesibindi, kanye nemicimbi ekhethekileko ebeyiphawula ukukhula. Wakhuluma iqiniso loke, iingcenye ezibudisi neengcenye ezihle. Iindaba zakhe zisikhumbuza bona kubayini kuqakathekile ukugcina umlando wethu uphila.",
        ve: "Bugu ya Credo Mutwa i na zwiitwa zwinzhi — zwa nyendo ndapfu, zwa maswole a re na tshivhindi, na mikosi yo khetheaho ye ya vha i tshi swaya u aluwa. O amba ngoho yoṱhe, masia a konḓaho na avhuḓi. Zwiitwa zwawe zwi ri humbudza uri ndi ngani zwi zwa ndeme u vhulunga ḓivhazwakale yashu i tshi tshila.",
      },
    },
  },

  vilakazi: {
    "mouth-to-page": {
      title: {
        af: "Van die Mond na die Bladsy",
        zu: "Kusuka Emlonyeni Kuya Ekhasini",
        xh: "Ukusuka Emlonyeni Ukuya Ephepheni",
        nso: "Go tšwa Molomong go ya Letlakaleng",
        st: "Ho tloha Molomong ho ea Leqepheng",
        ss: "Kusuka Emlonyeni Kuya Ekhasini",
        ts: "Ku suka Enonwini ku ya Etlukwini",
        nr: "Ukusuka Emlonyeni Ukuya Ekhasini",
        ve: "U bva Mulomoni u ya Siaṱarini",
      },
      text: {
        af: "Voor die drukpers het Zoeloe-geskiedenis in die monde van die izimbongi — die lofdigters — geleef, wat dit uit die geheue opgevoer het. In 1935 het B.W. Vilakazi Inkondlo kaZulu gepubliseer, die eerste bundel geskrewe Zoeloe-poësie, wat daardie mondelinge genie na die bladsy gedra het. Hy het met 'n moeilike vraag geworstel: hoe fikseer jy vertoning, geheue en asem in ink sonder om hul lewende wese te verloor?",
        zu: "Ngaphambi komshini wokunyathelisa, umlando wesiZulu wawuphila emilonyeni yezimbongi — abadumisi — ababewenza ngenhloko. Ngo-1935 uB.W. Vilakazi wanyathelisa u-Inkondlo kaZulu, umqulu wokuqala wezinkondlo zesiZulu ezibhaliwe, ethwala lobo bungcweti bomlomo aya ekhasini. Wabhekana nombuzo onzima: uwuqinisa kanjani umdlalo, inkumbulo, nomoya ku-inki ngaphandle kokulahlekelwa yingqikithi yakho ephilayo?",
        xh: "Phambi komatshini wokushicilela, imbali yesiZulu yayiphila emilonyeni yeimbongi — abadumisi — ababeyenza ngentloko. Ngo-1935 uB.W. Vilakazi wapapasha u-Inkondlo kaZulu, umqulu wokuqala wemibongo yesiZulu ebhaliweyo, ethwala obo bugcisa bomlomo aya ephepheni. Wajongana nombuzo onzima: uyiqinisa njani indlela yokwenza, inkumbulo, nomoya ku-inki ngaphandle kokulahlekelwa sisiqu sayo esiphilayo?",
        nso: "Pele ga motšhene wa go gatiša, histori ya Sezulu e be e phela melomong ya izimbongi — baopedi — bao ba bego ba e dira ka hlogo. Ka 1935 B.W. Vilakazi o gatišitše Inkondlo kaZulu, moqolo wa mathomo wa direto tša Sezulu tše di ngwadilwego, a rwala bokgoni bjoo bja molomo go ya letlakaleng. O ile a lwa le potšišo ye thata: o tiiša bjang tiragatšo, kgopolo le moya ka enke ntle le go lahlegelwa ke moko wa tšona wo o phelago?",
        st: "Pele ho motjhini oa ho hatisa, histori ya Sezulu e ne e phela melomong ya izimbongi — baroki — ba neng ba e etsa ka hlooho. Ka 1935 B.W. Vilakazi o hatisitse Inkondlo kaZulu, moqolo oa pele oa lithothokiso tsa Sezulu tse ngotsoeng, a jara bokgoni boo ba molomo ho ea leqepheng. O ile a loana le potso e thata: o tiisa joang tiragatso, mohopolo le moea ka enke ntle le ho lahleheloa ke moko oa tsona o phelang?",
        ss: "Ngaphambi kwemshini wekushicilela, umlandvo wesiZulu bewuphila emilonyeni yetimbongi — labadvumisi — lababewenta ngenhloko. Nga-1935 B.W. Vilakazi washicilela i-Inkondlo kaZulu, umculu wekucala wetinkondlo tesiZulu letibhaliwe, etfwala lobo bungcweti bemlomo aya ekhasini. Wabhekana nembuto lolukhuni: uwucinisa njani umdlalo, inkhumbulo, nemoya ku-inki ngaphandle kwekulahlekelwa yinsayeni yawo lephilako?",
        ts: "Emahlweni ka muchini wo kandziyisa, matimu ya Xizulu a ma hanya emilon'wini ya tinsimbongi — vadzunisi — lava a va ma endla hi nhloko. Hi 1935 B.W. Vilakazi u kandziyise Inkondlo kaZulu, buku yo sungula ya switlhokovetselo swa Xizulu leswi tsariweke, a rhwala vutshila byebyo bya nomu a ya etlukwini. U lwe ni xivutiso xo tika: u tiyisa njhani ku tlangiwa, ku tsundzuka, ni moya eka inki handle ko lahlekeriwa hi nchumu wa swona lowu hanyaka?",
        nr: "Ngaphambi komtjhini wokugadangisa, umlando wesiZulu bewuphila emilonyeni yezimbongi — abadumisi — ebebawenza ngehloko. Nga-1935 uB.W. Vilakazi wagadangisa i-Inkondlo kaZulu, umqulu wokuthoma weenkondlo zesiZulu ezitloliweko, athwala ubungcwethi bomlomo obo aya ekhasini. Waqalana nombuzo obudisi: uwuqinisa njani umdlalo, ikhumbulo, nomoya ku-inki ngaphandle kokulahlekelwa mumongo wawo ophilako?",
        ve: "Phanḓa ha muṱibi wa u gandisa, ḓivhazwakale ya Tshizulu yo vha i tshi tshila milomoni ya izimbongi — vharendi — vhe vha vha vha tshi i ita nga ṱhoho. Nga 1935 B.W. Vilakazi o gandisa Inkondlo kaZulu, bugu ya u thoma ya vhurendi ha Tshizulu ho ṅwaliwaho, a hwala vhutsila honovho ha mulomo a ya siaṱarini. O lwa na mbudziso khonḓaho: u khwaṱhisa hani u tambiwa, muhumbulo, na muya kha inki hu si na u xelelwa nga muya wazwo u tshilaho?",
      },
      childText: {
        af: "Lank gelede is Zoeloe-gedigte en -geskiedenis nie neergeskryf nie. Spesiale digters genaamd izimbongi het hulle onthou en hardop opgevoer. In 1935 het B.W. Vilakazi die eerste boek van Zoeloe-gedigte geskryf, genaamd Inkondlo kaZulu, sodat die gedigte ook op papier kan voortleef.",
        zu: "Endulo, izinkondlo nomlando wesiZulu kwakungabhalwanga phansi. Izimbongi ezikhethekile zazikukhumbula zikwenze ngezwi elikhulu. Ngo-1935, uB.W. Vilakazi wabhala incwadi yokuqala yezinkondlo zesiZulu, ebizwa ngo-Inkondlo kaZulu, ukuze izinkondlo ziphile nasephepheni.",
        xh: "Kudala, imibongo nembali yesiZulu yayingabhalwanga phantsi. Iimbongi ezikhethekileyo zaziyikhumbula ziyenze ngelizwi elikhulu. Ngo-1935, uB.W. Vilakazi wabhala incwadi yokuqala yemibongo yesiZulu, ebizwa ngo-Inkondlo kaZulu, ukuze imibongo iphile nasephepheni.",
        nso: "Kgale, direto le histori ya Sezulu di be di sa ngwalwe. Izimbongi tše di kgethegilego di be di di gopola gomme di di dira ka lentšu le legolo. Ka 1935, B.W. Vilakazi o ngwadile puku ya mathomo ya direto tša Sezulu, ye e bitšwago Inkondlo kaZulu, gore direto di phele le go letlakala.",
        st: "Kgale, lithothokiso le histori ya Sezulu li ne li sa ngoloe. Izimbongi tse kgethehileng li ne li li hopola ʼme li li etsa ka lentsoe le leholo. Ka 1935, B.W. Vilakazi o ngotse buka ya pele ya lithothokiso tsa Sezulu, e bitsoang Inkondlo kaZulu, e le hore lithothokiso li phele le leqepheng.",
        ss: "Endzabuko, tinkondlo nemlandvo wesiZulu bekungabhaliwe phansi. Timbongi letikhetsekile betitikhumbula titente ngelivi lelikhulu. Nga-1935, B.W. Vilakazi wabhala incwadzi yekucala yetinkondlo tesiZulu, lebitwa ngo-Inkondlo kaZulu, kuze tinkondlo tiphile nasekhasini.",
        ts: "Khale, switlhokovetselo ni matimu ya Xizulu a swi tsariwanga. Tinsimbongi to hlawuleka a ti swi tsundzuka ti swi endla hi rito lerikulu. Hi 1935, B.W. Vilakazi u tsale buku yo sungula ya switlhokovetselo swa Xizulu, leyi vuriwaka Inkondlo kaZulu, leswaku switlhokovetselo swi hanya ni le tlukwini.",
        nr: "Endulo, iinkondlo nomlando wesiZulu bekungatloliwe phasi. Izimbongi ezikhethekileko bezizikhumbula zizenze ngelizwi elikhulu. Nga-1935, uB.W. Vilakazi watlola incwadi yokuthoma yeenkondlo zesiZulu, ebizwa ngo-Inkondlo kaZulu, bona iinkondlo ziphile nasekhasini.",
        ve: "Kale, vhurendi na ḓivhazwakale ya Tshizulu zwo vha zwi sa ṅwaliwi. Izimbongi dzo khethaho dzo vha dzi tshi zwi humbula dza zwi ita nga ipfi ḽihulu. Nga 1935, B.W. Vilakazi o ṅwala bugu ya u thoma ya vhurendi ha Tshizulu, ine ya pfi Inkondlo kaZulu, uri vhurendi vhu tshile na siaṱarini.",
      },
    },
    "why-preservation": {
      title: {
        af: "Waarom Bewaring Saak Maak",
        zu: "Kungani Ukulondoloza Kubalulekile",
        xh: "Kutheni Ukulondolozwa Kubalulekile",
        nso: "Ke ka Lebaka la Eng go Boloka go le Bohlokwa",
        st: "Hobaneng ho Boloka ho le Bohlokwa",
        ss: "Kungani Kulondvolota Kubalulekile",
        ts: "Ha Yini ku Hlayisa ku ri ka Nkoka",
        nr: "Kubayini Ukulonda Kuqakathekile",
        ve: "Ndi Ngani u Vhulunga zwi zwa Ndeme",
      },
      text: {
        af: "Vilakazi se prestasie was ook 'n waarskuwing. 'n Taal wat nie geskryf, nie onderrig, nie hernu word nie, kan vervaag. Deur die izimbongi van asem na boek te skuif, het hy die lewe van Zoeloe-letterkunde verleng — net soos daardie selfde erfenis vandag van boek na skerm moet skuif. Dit is die geslagslyn waarby Ubuntu Heritage aansluit: nog 'n daad van bewaring, op die mense se eie voorwaardes.",
        zu: "Impumelelo kaVilakazi yayiphinde iyisixwayiso. Ulimi olungabhalwa, olungafundiswa, olungavuselelwa lungafiphala. Ngokususa izimbongi kusuka emoyeni ziye encwadini, welula impilo yezincwadi zesiZulu — njengoba nalelo fa namuhla kufanele lisuke encwadini liye esikrinini. Yilo lolu hlu lwozalo uUbuntu Heritage ejoyina kulo: esinye isenzo sokulondoloza, ngokwemibandela yabantu uqobo.",
        xh: "Impumelelo kaVilakazi yayikwasisilumkiso. Ulwimi olungabhalwayo, olungafundiswayo, olungahlaziywayo lungabuna. Ngokususa iimbongi kwimoya ziye encwadini, wolula ubomi boncwadi lwesiZulu — njengoko nelo lifa namhlanje kufuneka lisuke encwadini liye kwisikrini. Lolu luluhlu lomnombo uUbuntu Heritage alujoyinayo: esinye isenzo sokulondoloza, ngokwemiqathango yabantu ngokwabo.",
        nso: "Katlego ya Vilakazi e be gape e le temošo. Leleme leo le sa ngwalwego, le sa rutwego, le sa mpshafatšwego le ka fifala. Ka go šuthiša izimbongi go tšwa moyeng go ya pukung, o okeditše bophelo bja dingwalwa tša Sezulu — bjalo ka ge bohwa bjona bjo lehono bo swanetše go šutha go tšwa pukung go ya sekirineng. Ke wona molokwana wo Ubuntu Heritage e o tsenago go wona: tiro ye nngwe ya go boloka, ka melao ya batho ka bobona.",
        st: "Katleho ya Vilakazi e ne hape e le temoso. Puo e sa ngoloeng, e sa rutoeng, e sa nchafatsoeng e ka fifala. Ka ho suthisa izimbongi ho tloha moeeng ho ea bukeng, o ekelitse bophelo ba lingoliloeng tsa Sezulu — joalo ka ha lefa leo la kajeno le lokela ho suthela bukeng ho ea skirineng. Ke oona moloko oo Ubuntu Heritage e kenang ho oona: ketso e ʼngoe ya ho boloka, ka melao ya batho ka bobona.",
        ss: "Impumelelo yaVilakazi beyiphindze iyisexwayiso. Lulwimi lolungabhalwa, lolungafundziswa, lolungavuselelwa lungafiphala. Ngekususa timbongi kusuka emoyeni tiye encwadzini, welula imphilo yetincwadzi tesiZulu — njengoba nalelo lifa lamuhla kufanele lisuke encwadzini liye esikrinini. Yilona lolu luhlu lwetitukulwane Ubuntu Heritage lelijoyina kulo: lesinye sento sekulondvolota, ngekwemibandzela yebantfu ngekwabo.",
        ts: "Ku humelela ka Vilakazi a ku tlhela ku ri xitsundzuxo. Ririmi leri nga tsariwiki, leri nga dyondzisiwiki, leri nga vuseleriwiki ri nga dzwihala. Hi ku susumeta tinsimbongi ku suka emoya ti ya ebukwini, u engetele vutomi bya matsalwa ya Xizulu — tanihi leswi ni ndzhaka yoleyo namuntlha yi faneleke ku suka ebukwini yi ya exikirinini. I wona ntukulu lowu Ubuntu Heritage yi nghenaka eka wona: xiendlo xin'wana xa ku hlayisa, hi milawu ya vanhu hi voxe.",
        nr: "Impumelelo kaVilakazi beyiphinde iyisiyeleliso. Ilimi elingatloliwa, elingafundiswa, elingavuselelwa lingafiphala. Ngokususa izimbongi kusuka emmoyeni ziye encwadini, welula ipilo yeencwadi zesiZulu — njengombana nelo lifa namhlanjesi kufanele lisuke encwadini liye esikrinini. Ngiwo lo mongo wesizukulwana uUbuntu Heritage ejoyina kuwo: esinye isenzo sokulonda, ngokwemibandela yabantu ngokwabo.",
        ve: "U bvelela ha Vilakazi ho vha hafhu tsevho. Luambo lu songo ṅwaliwaho, lu songo funzwaho, lu songo swayaho lu nga fhifhala. Nga u pfulusela izimbongi u bva muyani u ya bugwuni, o engedza vhutshilo ha maṅwalwa a Tshizulu — samusi ifa iḽo ṋamusi ḽi tshi tea u pfuluwa u bva bugwuni u ya sikirinini. Ndi wonoyu mutevhe wa lushaka une Ubuntu Heritage ya dzhena khawo: tshiito tshiṅwe tsha u vhulunga, nga milayo ya vhathu vhe vhone.",
      },
      childText: {
        af: "Vilakazi het iets belangriks gewys: as ons nie ons tale neerskryf en deel nie, kan hulle verdwyn. Hy het gehelp dat Zoeloe-poësie in boeke voortleef. Vandag help toepassings soos hierdie een daardie selfde erfenis om op skerms voort te leef — sodat dit nooit verlore gaan nie.",
        zu: "UVilakazi wabonisa okuthile okubalulekile: uma singazibhali futhi sabelane ngezilimi zethu, zinganyamalala. Wasiza izinkondlo zesiZulu ukuba ziqhubeke ziphila ezincwadini. Namuhla, izinhlelo zokusebenza ezifana nalezi zisiza lelo fa ukuba liqhubeke liphila ezikrinini — ukuze lingalokothi lilahleke.",
        xh: "UVilakazi wabonisa into ebalulekileyo: ukuba asiwabhali kwaye sabelane ngeelwimi zethu, zinokunyamalala. Wanceda imibongo yesiZulu ukuba iqhubeke iphila kwiincwadi. Namhlanje, iinkqubo ezifana nale zinceda elo lifa ukuba liqhubeke liphila kwizikrini — ukuze lingaze lilahleke.",
        nso: "Vilakazi o bontšhitše selo se bohlokwa: ge re sa ngwale ebile re abelane maleme a rena, a ka nyamelela. O thušitše direto tša Sezulu go tšwela pele di phela ka dipuku. Lehono, dithulaganyo tše di swanago le ye di thuša bohwa bjoo go tšwela pele bo phela dikirineng — gore bo se ke bja lahlega.",
        st: "Vilakazi o bontšitse ntho ea bohlokoa: haeba re sa ngole ʼme ra arolelana lipuo tsa rona, li ka nyamela. O thusitse lithothokiso tsa Sezulu ho tsoela pele li phela libukeng. Kajeno, mananeo a kang ena a thusa lefa leo ho tsoela pele le phela likirineng — e le hore le se ke la lahleha.",
        ss: "Vilakazi wakhombisa intfo lebalulekile: nangabe singatibhali futsi sabelane ngetilwimi tetfu, tingashabalala. Wasita tinkondlo tesiZulu kutsi tichubeke tiphila etincwadzini. Lamuhla, tinhlelo tekusebenta letifana naletgi tisita lelo lifa kutsi lichubeke liphila etikrinini — kuze lingaze lilahleke.",
        ts: "Vilakazi u kombise xilo xa nkoka: loko hi nga tsari naswona hi avelana tindzimi ta hina, ti nga nyamalala. U pfune switlhokovetselo swa Xizulu ku ya emahlweni swi hanya etibukwini. Namuntlha, tinhlelo to fana ni leti ti pfuna ndzhaka yoleyo ku ya emahlweni yi hanya etikirinini — leswaku yi nga tshuki yi lahleka.",
        nr: "UVilakazi watjengisa into eqakathekileko: nasingazitloli begodu sabelane ngeenlimi zethu, zingatjhabalala. Wasiza iinkondlo zesiZulu bona ziragele phambili ziphila eencwadini. Namhlanjesi, iinhlelo ezifana nalezi zisiza ilifa elo bona liragele phambili liphila eenkrinini — bona lingalahleki.",
        ve: "Vilakazi o sumbedza tshithu tsha ndeme: arali ri sa ṅwali nahone ra kovhelana nyambo dzashu, dzi nga ngala. O thusa vhurendi ha Tshizulu uri vhu bvele phanḓa vhu tshila kha dzibugu. Ṋamusi, thandela dzi ngaho idzi dzi thusa ifa iḽo uri ḽi bvele phanḓa ḽi tshila kha sikirini — uri ḽi si vhuye ḽa xela.",
      },
    },
  },
};
