import React from "react";
import { View, StyleSheet } from "react-native";
import { Lang } from "../content/types";
import { allModules } from "../content";
import { t } from "../i18n";
import { Screen, ScreenHeader, Card, Title, Body, Meta, Muted } from "../ui";
import { spacing } from "../theme/tokens";

// "About the Sources" — credits every author + text, states adaptation vs original, and labels AI
// images as interpretations. Earns Humanities Depth + the "acknowledge sources" ethics rule.
// See docs/04-humanities-sources.md + .claude/skills/humanities-grounding. Built on the UI kit.

const UI = {
  title: { en: "About the Sources", tn: "Ka ga Metswedi" },
  intro: {
    en: "Maloba is grounded in real, foundational South African texts — not generic summaries. Every story credits its author and source, and we follow one rule: truth only, no invented history.",
    tn: "Maloba e theilwe mo dikwalong tsa nnete tsa motheo tsa Aforika Borwa — e seng dikgutsufatso fela. Kanegelo nngwe le nngwe e tlotla mokwadi le motswedi wa yone, mme re sala morago molao o le mongwe: nnete fela, ga go na hisitori e e itlhametsweng.",
  },
  disclaimer: {
    en: "Scene images are generated by AI as artistic interpretations — they are not historical photographs or depictions of real people.",
    tn: "Ditshwantsho tsa diteng di dirwa ke AI e le dikakanyo tsa botaki — ga se dinepe tsa hisitori kgotsa ditshwantsho tsa batho ba mmatota.",
  },
  references: { en: "References", tn: "Metswedi" },
};

export function AboutSourcesScreen({ lang, onBack }: { lang: Lang; onBack: () => void }) {
  return (
    <Screen tone="paper">
      <ScreenHeader kicker="Acknowledgements" title={t(UI.title, lang)} onBack={onBack} />

      <Body style={styles.intro}>{t(UI.intro, lang)}</Body>

      {allModules.map((m) => (
        <Card key={m.id} style={styles.card}>
          <Title>{m.title}</Title>
          <Meta style={styles.meta}>
            {m.author}
            {m.year ? ` · ${m.year}` : ""}
          </Meta>
          <Muted style={styles.source}>{m.source}</Muted>
          <Meta style={styles.refLabel}>{t(UI.references, lang)}</Meta>
          {m.references.map((r, i) => (
            <Muted key={i} style={styles.refItem}>
              • {r}
            </Muted>
          ))}
        </Card>
      ))}

      <Card style={styles.disclaimer}>
        <Muted style={styles.disclaimerText}>{t(UI.disclaimer, lang)}</Muted>
      </Card>
    </Screen>
  );
}

const styles = StyleSheet.create({
  intro: { marginBottom: spacing.lg },
  card: { marginBottom: spacing.md },
  meta: { marginTop: 2 },
  source: { fontStyle: "italic", marginTop: spacing.xs },
  refLabel: { marginTop: spacing.md },
  refItem: { marginTop: 4 },
  disclaimer: { marginTop: spacing.sm },
  disclaimerText: { fontStyle: "italic" },
});
