// Turn the Expo web export into an installable, offline-capable PWA.
//
// WHY A POST-STEP. This app does not use Expo Router, so there is no `+html.tsx` to put head tags in,
// and Expo generates `dist/index.html` itself. Rather than inject the manifest link from JS at
// runtime — which works for some browsers and not others, and always races the first paint — this
// rewrites the generated HTML after the export, so the served document is correct before any script
// runs. Run it via `npm run build:web`, which is what the Vercel build command calls.
//
// WHY THIS SERVICE WORKER IS CONSERVATIVE. A service worker on a live site is sticky: once a bad one
// is installed it can keep serving stale files to a real person long after the bug is fixed. So:
//
//   * navigation and HTML are NETWORK-FIRST — a deploy is picked up the moment someone is online,
//     and the cached shell is only used when the network genuinely fails;
//   * only content-hashed files under /_expo/static/ are cache-first, because their names change
//     whenever their contents do, so a stale hit is impossible;
//   * `skipWaiting` + `clients.claim` mean the next deploy replaces a broken worker immediately
//     instead of waiting for every tab to close.
//
// WHAT IS PRECACHED, AND WHAT IS NOT. The shell only: the HTML, the JS bundles, the icons. Those are
// bytes the browser has just downloaded to render the page, so precaching them costs almost nothing
// extra. Images and audio are NOT precached — they fill the cache as they are actually viewed. On a
// metered connection, downloading the whole archive on first open would be the opposite of the point.

import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { createHash } from "node:crypto";

const DIST = new URL("../dist/", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const MARKER = "<!-- pwa:injected -->";

if (!existsSync(join(DIST, "index.html"))) {
  console.error("dist/index.html not found — run `npx expo export --platform web` first.");
  process.exit(1);
}

/** Every file in dist, as a root-relative URL path. */
function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else out.push("/" + relative(DIST, p).split(/[\\/]/).join("/"));
  }
  return out;
}

const all = walk(DIST);

// The shell: the document, the JS that renders it, and the icons an installed app needs.
const shell = [
  "/",
  "/index.html",
  ...all.filter((f) => f.startsWith("/_expo/static/js/web/") && f.endsWith(".js")),
  ...all.filter((f) => /^\/icon-.*\.png$/.test(f)),
  "/manifest.webmanifest",
  "/favicon.ico",
].filter((f, i, a) => a.indexOf(f) === i && (f === "/" || all.includes(f)));

// A build id derived from the shell itself, so the cache rolls over exactly when the app changes
// and not one deploy more often than that.
const buildId = createHash("sha256").update(shell.join("|")).digest("hex").slice(0, 12);

// ── index.html ───────────────────────────────────────────────────────────────
let html = readFileSync(join(DIST, "index.html"), "utf8");

if (html.includes(MARKER)) {
  console.log("index.html already processed — skipping injection.");
} else {
  const head = `${MARKER}
    <link rel="manifest" href="/manifest.webmanifest" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="South Africa's foundational literature and heritage — vivid, multilingual and free." />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="apple-mobile-web-app-title" content="Ubuntu" />
    <link rel="apple-touch-icon" href="/icon-192.png" />
    <script>
      // Registered after load so it never competes with the first paint for bandwidth — the point of
      // this worker is the SECOND visit, not the first.
      if ("serviceWorker" in navigator) {
        window.addEventListener("load", function () {
          navigator.serviceWorker.register("/sw.js").catch(function () {
            /* An unavailable worker is not an error the reader should ever see. */
          });
        });
      }
    </script>
  `;
  html = html.replace("</head>", head + "</head>");
  writeFileSync(join(DIST, "index.html"), html, "utf8");
}

// ── sw.js ────────────────────────────────────────────────────────────────────
const sw = `// Generated by scripts/build-web.mjs — do not edit by hand.
const CACHE = "ubuntu-heritage-${buildId}";
const SHELL = ${JSON.stringify(shell, null, 2)};

self.addEventListener("install", (e) => {
  self.skipWaiting();
  e.waitUntil(
    caches.open(CACHE).then((c) =>
      // One failed file must not fail the whole install, or a single 404 leaves the reader with no
      // offline app at all.
      Promise.allSettled(SHELL.map((u) => c.add(new Request(u, { cache: "reload" }))))
    )
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // never touch Pollinations, fonts, anything remote

  // Navigations: network first, cached shell only when the network actually fails. This is what
  // stops a stale worker from pinning someone to an old build.
  if (req.mode === "navigate") {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put("/index.html", copy));
          return res;
        })
        .catch(() => caches.match("/index.html").then((r) => r || Response.error()))
    );
    return;
  }

  // Content-hashed build output: cache first, safely — the name changes whenever the bytes do.
  if (url.pathname.startsWith("/_expo/static/")) {
    e.respondWith(
      caches.match(req).then(
        (hit) =>
          hit ||
          fetch(req).then((res) => {
            if (res.ok) {
              const copy = res.clone();
              caches.open(CACHE).then((c) => c.put(req, copy));
            }
            return res;
          })
      )
    );
    return;
  }

  // Bundled media: cache as it is genuinely viewed, never up front. This is the low-data promise —
  // a story you have read once costs nothing to read again.
  if (url.pathname.startsWith("/assets/") || /\\.(png|jpg|jpeg|webp|mp3|mp4|ttf|otf|woff2?)$/i.test(url.pathname)) {
    e.respondWith(
      caches.match(req).then(
        (hit) =>
          hit ||
          fetch(req).then((res) => {
            if (res.ok) {
              const copy = res.clone();
              caches.open(CACHE).then((c) => c.put(req, copy));
            }
            return res;
          }).catch(() => hit || Response.error())
      )
    );
    return;
  }
  // Everything else goes to the network untouched.
});
`;

writeFileSync(join(DIST, "sw.js"), sw, "utf8");

const shellBytes = shell
  .filter((f) => f !== "/")
  .reduce((n, f) => n + (existsSync(join(DIST, f)) ? statSync(join(DIST, f)).size : 0), 0);

console.log(`PWA ready — build ${buildId}`);
console.log(`  shell: ${shell.length} files, ${(shellBytes / 1024 / 1024).toFixed(2)} MB precached`);
console.log(`  total in dist: ${all.length} files, ${(all.reduce((n, f) => n + statSync(join(DIST, f)).size, 0) / 1024 / 1024).toFixed(2)} MB`);
